"""add assignments deleted_at

Revision ID: feccfb30f615
Revises: e3b4c92cf967
Create Date: 2026-04-20 12:52:54.819127+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feccfb30f615'
down_revision: Union[str, None] = 'e3b4c92cf967'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignments', 'deleted_at')
    # ### end Alembic commands ###
